-- Ensure target database exists and use it
CREATE DATABASE IF NOT EXISTS `inserq_db_new` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `inserq_db_new`;

RENAME TABLE `is_elements` TO `is_elements_backup_20260115155336`; -- backup old table if exists

CREATE TABLE `is_elements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) ,
  `family` VARCHAR(64) ,
  `group` VARCHAR(64) ,
  `synonyms` VARCHAR(255) ,
  `iso` VARCHAR(255) ,
  `origin` VARCHAR(80) ,
  `length` INT,
  `tam` VARCHAR(64) ,
  `le_cleavage_site` VARCHAR(64) ,
  `re_cleavage_site` VARCHAR(64) ,
  `orf1` VARCHAR(64) ,
  `orf2` VARCHAR(64) ,
  `accession_number` VARCHAR(64) ,
  `mge_type` VARCHAR(64) ,
  `related_element_s` VARCHAR(255) ,
  `isoform` VARCHAR(255) ,
  -- removed legacy synonym_s, use `synonyms` instead
  -- removed duplicate secondary fields: name2, family2, group2, accession_number2, origin2
  `host` VARCHAR(64) ,
  `transposition` VARCHAR(255) ,
  `is_sequence` TEXT,
  `is_length` INT,
  `orf_number` INT,
  `orf_1` INT,
  `orf_1_length` INT,
  `orf_1_begin` INT,
  `orf_1_end` INT,
  `orf_1_strand` VARCHAR(64) ,
  `fusion_orf_1` VARCHAR(64) ,
  `orf_1_function` VARCHAR(64) ,
  `orf_1_chemistry` VARCHAR(64) ,
  `orf_1_sequence` VARCHAR(254) ,
  `orf_2` INT,
  `orf_2_length` INT,
  `orf_2_begin` INT,
  `orf_2_end` INT,
  `orf_2_strand` VARCHAR(64) ,
  `fusion_orf_2` VARCHAR(64) ,
  `orf_2_function` VARCHAR(64) ,
  `orf_2_chemistry` VARCHAR(64) ,
  `orf_2_sequence` TEXT,
  `comment` LONGTEXT,
  `references` LONGTEXT,
  `submitter_first_name` VARCHAR(50) ,
  `submitter_last_name` VARCHAR(50) ,
  `submitter_institution` VARCHAR(200) ,
  `submitter_department` VARCHAR(200) ,
  `submitter_postal_address` VARCHAR(300) ,
  `submitter_postal_code` VARCHAR(20) ,
  `submitter_country` VARCHAR(100) ,
  `submitter_email` VARCHAR(200) ,
  `submitter_telephone` VARCHAR(50) ,
  `submitter_id` INT,
  `reviewer_id` INT,
  `submission_date` DATETIME,
  `review_date` DATETIME,
  `review_comment` LONGTEXT,
  `status` ENUM('pending','approved','rejected') DEFAULT 'pending',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_name` (`name`),
  KEY `idx_family` (`family`),
  KEY `idx_group` (`group`),
  KEY `idx_host` (`host`),
  KEY `idx_status` (`status`),
  KEY `idx_submitter` (`submitter_id`),
  KEY `idx_accession` (`accession_number`),
  KEY `reviewer_id` (`reviewer_id`),
  KEY `idx_is_status_family` (`status`,`family`),
  KEY `idx_is_status_host` (`status`,`host`),
  FULLTEXT KEY `idx_search` (`name`,`family`,`group`,`host`,`comment`),

  CONSTRAINT `is_elements_ibfk_1` FOREIGN KEY (`submitter_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `is_elements_ibfk_2` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
